### ISSUE TITLE
Panic if len of pattern more than input value.

### ISSUE THREAD

**Issue by gebv** [gebv/strparam#1]
Pattern `#snippet-{boundary}`
Parse `foobar`

```
panic: runtime error: slice bounds out of range [:9] with length 6

goroutine 1 [running]:
github.com/gebv/strparam.(*PatternSchema).Lookup(0xc000060180, 0x4c467b, 0x6, 0x0, 0x0, 0x557c00, 0xc000032778)
	/tmp/gopath511142750/pkg/mod/github.com/gebv/strparam@v0.0.2/strparam.go:154 +0x704
main.main()
	/tmp/sandbox926670139/prog.go:12 +0x5d
```

**Comment by gebv** [comment]
Len of pattern more than input value.
